# conda env create -f environment.yml
name: lume-impact-dev
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - pip
  - openpmd-beamphysics
  - lume-base
  - distgen
  - matplotlib
  - bokeh
  - jupyter_bokeh
  - impact-t=*=mpi_openmpi*
  #- impact-t=*=mpi_mpich*
# Developer
  - jupyterlab>=3
  - ipywidgets
  - pygments
